version: "3.3"

services:
  worker-01:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  worker-02:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .
  
  worker-03:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  worker-04:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  balancer-host:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  master-ansible:
    image: lexauw/ansible-alpine  
    volumes:
      - ./inventory.txt:/etc/ansible/hosts:ro
      - ./:/app:ro
