version: "3.3"

services:
  worker-01:
    image: eugenes1/python-sshd

  worker-02:
    image: eugenes1/python-sshd
  
  worker-03:
    image: eugenes1/python-sshd

  worker-04:
    image: eugenes1/python-sshd

  master-ansible:
    image: lexauw/ansible-alpine  
    volumes:
      - ./inventory.txt:/etc/ansible/hosts