version: "3.3"

services:
  worker-01:
    image: davidlor/python-ssh

  worker-02:
    image: davidlor/python-ssh
  
  worker-03:
    image: davidlor/python-ssh

  worker-04:
    image: davidlor/python-ssh

  master-ansible:
    image: lexauw/ansible-alpine  
    volumes:
      - ./inventory.txt:/etc/ansible/hosts:ro
      - ./:/app:ro
