version: "3.3"

services:
  redis:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  mongodb:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  jupyter:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .
    ports:
      - 8888:8888

  balancer:
    build:
      dockerfile: python-sshd.Dockerfile
      context: .

  master-ansible:
    image: lexauw/ansible-alpine  
    volumes:
      - ./inventory.txt:/etc/ansible/hosts:ro
      - ./:/app:ro
